# -*- mode: ruby -*-

tap 'd12frosted/emacs-plus'
tap 'caskroom/cask'
tap 'caskroom/fonts'

cask_args appdir: '/Applications'

brew 'automake'
brew 'ctags'
brew 'bash'
# After installing emacs-plus:
# $ ln -s /usr/local/Cellar/emacs-plus/*/Emacs.app/ /Applications/
brew 'emacs-plus'
brew 'git'
brew 'python'
brew 'hub'
brew 'isync'
brew 'libyaml'
brew 'markdown'
brew 'openssl'
brew 'postgres'
brew 'rbenv'
brew 'ripgrep'
brew 'reattach-to-user-namespace' # vim / tmux integration
brew 'redis'
brew 'the_silver_searcher'
brew 'tmux'
brew 'trash'
brew 'tree'
brew 'vim'
brew 'w3m'
brew 'gpg'
brew 'pinentry-mac'
# brew 'global'
brew 'fasd'
brew 'z'
brew 'stow'
brew 'asciiquarium'
brew 'pass'
brew 'awscli'
# brew 'drafter' # for apib files
# brew 'mas'     # install os apps from the CLI
brew 'terminal-notifier'
brew 'bash-completion'
brew 'prettier'

cask 'caffeine'
cask 'dash'
cask 'disk-inventory-x'
cask 'flux'
cask 'google-chrome'
cask 'iterm2'
cask 'karabiner-elements'
cask 'slack'
cask 'gpg-suite'
cask 'font-fira-code'
cask 'font-source-code-pro'
cask 'ngrok'
cask 'postgres' # postgresapp
cask 'awareness'

cask 'shiftit'
cask 'flycut'  # clipboard history
cask 'jetbrains-toolbox'

cask 'tenor' # gifs
cask 'docker'

cask 'java'
brew 'scala'

# brew 'msmtp'                     # email stuff
# brew 'mu', args: ['with-emacs']  # email stuff
# cask 'growlnotify'
# cask 'imageoptim'
# cask 'bettertouchtool'
# cask 'upterm'
# cask 'charles'                   # proxy / HTTP inspector
# cask 'cocoapacketanalyzer'
